// --- SEMANTIC DSL INTERFACES ---

export type HipSemantic = 'forward_max' | 'forward' | 'neutral' | 'backward' | 'backward_max';
export type KneeSemantic = 'retracted_max' | 'retracted' | 'neutral' | 'extended' | 'extended_max';

export interface LegSemanticState {
    hip: HipSemantic;
    knee: KneeSemantic;
}

export interface SemanticPose {
    duration: number; // in milliseconds
    legs: {
        FR: LegSemanticState; // Front Right
        FL: LegSemanticState; // Front Left
        BR: LegSemanticState; // Back Right
        BL: LegSemanticState; // Back Left
    };
}

export interface ActionScript {
    thought?: string;
    actionName?: string;
    steps: SemanticPose[];
}

// --- TRANSLATION TABLES ---
// Mapping semantic terms to exact servo angles based on RobotAnimator physics
// 90 is always neutral.

const HIP_MAP: Record<HipSemantic, number> = {
    'forward_max': 140, // Extreme forward sweep
    'forward': 115,     // Moderate forward
    'neutral': 90,      // Center
    'backward': 65,     // Moderate backward
    'backward_max': 40  // Extreme backward sweep
};

const KNEE_MAP: Record<KneeSemantic, number> = {
    'retracted_max': 150, // Leg pulled up tightly to body
    'retracted': 120,    // Leg lifted
    'neutral': 90,       // Standing height
    'extended': 60,      // Leg pushed down/standing taller
    'extended_max': 30   // Leg fully straight down
};

// --- ACTION PARSER ---
export class ActionParser {

    /**
     * Parses the semantic JSON generated by the LLM into safe, raw JavaScript 
     * code that calls animator.enqueueMove() with exact 8-element arrays.
     */
    static generateAnimScript(script: ActionScript): string {
        if (!script || !script.steps || !Array.isArray(script.steps)) {
            throw new Error("Invalid ActionScript: missing steps array.");
        }

        let jsString = "";

        script.steps.forEach((pose, _index) => {
            const arr = this.poseToArray(pose);
            // Fallback duration to 500ms if not explicitly provided or invalid
            const dur = (typeof pose.duration === 'number' && pose.duration > 0) ? pose.duration : 500;

            jsString += 'animator.enqueueMove(' + dur + ', [' + arr.join(', ') + ']);\n';
        });

        // Always ensure a safe return to home pose at the end
        jsString += 'animator.enqueueMove(500, [90, 90, 90, 90, 90, 90, 90, 90]);\n';

        return jsString;
    }

    /**
     * Converts a SemanticPose object into the strict 8-length array needed by enqueueMove.
     * Index mapping from animator:
     * 0: FR_Hip, 1: FL_Hip, 2: FL_Knee, 3: FR_Knee, 
     * 4: BR_Hip, 5: BL_Hip, 6: BR_Knee, 7: BL_Knee
     * 
     * Note the confusing knee order in the original script:
     * 0=FR_Hip, 1=FL_Hip
     * 2=FL_Knee, 3=FR_Knee (Notice FL is 2, FR is 3)
     * 4=BR_Hip, 5=BL_Hip
     * 6=BR_Knee, 7=BL_Knee
     */
    private static poseToArray(pose: SemanticPose): number[] {
        const arr = new Array(8).fill(90); // default to neutral

        // Helper to safely get angle, defaulting to 90 if LLM hallucinates a bad string
        const safeHip = (val: any) => HIP_MAP[val as HipSemantic] ?? 90;
        const safeKnee = (val: any) => KNEE_MAP[val as KneeSemantic] ?? 90;

        if (pose.legs) {
            // Hips (X-axis)
            if (pose.legs.FR) arr[0] = safeHip(pose.legs.FR.hip);
            if (pose.legs.FL) arr[1] = safeHip(pose.legs.FL.hip);
            if (pose.legs.BR) arr[4] = safeHip(pose.legs.BR.hip);
            if (pose.legs.BL) arr[5] = safeHip(pose.legs.BL.hip);

            // Knees (Z-axis) - Note the swapped index 2 and 3 based on original code
            if (pose.legs.FL) arr[2] = safeKnee(pose.legs.FL.knee);
            if (pose.legs.FR) arr[3] = safeKnee(pose.legs.FR.knee);
            if (pose.legs.BR) arr[6] = safeKnee(pose.legs.BR.knee);
            if (pose.legs.BL) arr[7] = safeKnee(pose.legs.BL.knee);
        }

        return arr;
    }
}
